version: '3'
services:
  web:
    build: .
    ports: "3000:3000"
    volumes: .:/app
    command: bundle exec rails s -p 3000
    links:
      - db
    environment:
      DATABASE_URL: postgres://db:5432
  db:
    image: postgres:9.6.3
