vault: &vault
  github:
    access_token: AQICAHhpNXRNHKzg0fWh6iaZOuC2EXk8IpHmy0BCJq8g0JIKVgFDiDbUPoDTeYv6rrWl2kntAAAAkTCBjgYJKoZIhvcNAQcGoIGAMH4CAQAweQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAztiEz/KvqC9lg4ZwkCARCATAgURPHWNn0u5eGhedwdOQ+SZOzL424W09qj2awocLpk7I2GPeqMu50gwMDlRdgG3m//KsOks1rsVGLAIQEzfUU9lSvcgmuAKwWhUgA=
  secret_key_base: AQICAHhpNXRNHKzg0fWh6iaZOuC2EXk8IpHmy0BCJq8g0JIKVgERtujmHwmDJFZZn+1T5fktAAAA7DCB6QYJKoZIhvcNAQcGoIHbMIHYAgEAMIHSBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDEOauG1b6cDdPDSsggIBEICBpBB/p4O31ran7hk5lm0EcN64dMT8Fv7aZru2dbyLibRppPdALBHRKL6U46t4Q2v2rbjLkHGYCAG/GiathEo8oUoNMlqxcvahqzegAxCSkW3fo/gnfSaMzyAkB4VUsE2EYsdzODruvwfDKi3UENQ5lC1hbhTUYYXnwyHfeJQxWKmq7RuTLNVzOUr7FJG8FHhR3tkULiLXr5OHLVG5omOZXV0m4bxS
  sentry:
    dsn: AQICAHhpNXRNHKzg0fWh6iaZOuC2EXk8IpHmy0BCJq8g0JIKVgFyUrRLuxZgKS4sCuMx5MotAAAAxTCBwgYJKoZIhvcNAQcGoIG0MIGxAgEAMIGrBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPk+NPdr8TKsyHjuAwIBEIB+B50UGh/MZc6ypo0ce7Gwv4+qjUkXca5cY7Mxm7+upkeZFBEoqn1gDBG20RGE8d27yWbrXbyIvheVOI2EYnG81RHaUnSzEbD2R63gG4kp/pDVI98EIJFS8mCrtlIgaghPnRtFmvWEr4itYlgPKs6O1Wl5t00j5haDKkqn1fFW
development:
  <<: *vault
test:
  <<: *vault
production:
  <<: *vault
