vault: &vault
  github:
    access_token: AQICAHhpNXRNHKzg0fWh6iaZOuC2EXk8IpHmy0BCJq8g0JIKVgE4HtezjUbCZ3u11/7/GY4TAAAAkTCBjgYJKoZIhvcNAQcGoIGAMH4CAQAweQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxHcJl1Fv5WT5VuZRQCARCATA2yp+eNGBY7ciemuT6JU0D8Ch4QcgHGAG1B8hzugZ9vNa36BQ8VSQSb5WiBXtdJJaTDs7krekkcAhTfv6YFg8yGk3RFk8+AI8ZK1wg=
  secret_key_base: AQICAHhpNXRNHKzg0fWh6iaZOuC2EXk8IpHmy0BCJq8g0JIKVgH8Fr75a3ngDmzjFtRGVMEmAAAA7DCB6QYJKoZIhvcNAQcGoIHbMIHYAgEAMIHSBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNMK53vnfEbGdedYKwIBEICBpAVOYRojukNvoUcQMfcW+hiaqkjJD0pqLWUiKlKSVDp89hIcFx96sEDL8qo7dZSL60mHV/0cezJzEwM6e58hLSoUi+/xgcdDb8V8SVI+t7lk0WM4LuZ8PnzxG4YnUQ4poLhdwM0VsdqhvxcdOkwEv5Ah1r6CBbKCGJfl+/5MZI/xIVOlfjnCa8AfWNOfSRK8YeOJ0LbqASAeF7C4KUwfwU+vZL/F
development:
  <<: *vault
test:
  <<: *vault
production:
  <<: *vault
