defaults: &defaults
  repository:
    orders:
      - stargazers_count
      - forks_count
      - pushed_at
  bulk_importer:
    user_columns:
      - login
      - avatar_url
      - html_url
    repository_columns:
      - name
      - name_with_owner
      - description
      - html_url
      - stargazers_count
      - forks_count
      - pushed_at
  redis:
    url: redis://localhost:6379/1
  sidekiq:
    client_size: 2
    server_size: 2
  yaml_vault:
    key:
      -
        - $
        - vault
    cryptor: aws-kms
    aws_kms_key_id: alias/rails-showcase

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
